"use strict";

// Shared functions in ../shared/_shared.js file

/* - Write in PSEUDO CODE - */
/* - Write in PSEUDO CODE -
ARRAY;

MOST_FREQUENT;
CURRENT_FREQUENCY;
HIGHEST_FREQUENCY;

LOOP ARRAY {
  INCREASE CURRENT_FREQUENCY;
  IF (CURRENT ELEMENT IS LAST OF ITS KIND) {
    IF (CURRENT_FREQUENCY > HIGHEST_FREQUENCY) {
      HIGHEST_FREQUENCY IS EQUAL TO CURRENT_FREQUENCY;
      MOST_FREQUENT = CURRENT_ELEMENT;
    }
    CURRENT_FREQUENCY RESETS TO ZERO;
  }
}
*/